import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    width: "100vw",
    height: "100vh",
    position: "absolute",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontFamily: tokens.fontFamilyBase,
  },
  appContentContainer: {
    position: "relative",
    width: "100vw",
    height: "calc(100vh - 30px)",
  },
  barContainer: {
    width: "100%",
    height: "30px",
    display: "flex",
    alignItems: "center",
    position: "relative",
    justifyContent: "space-between",
    backgroundColor: tokens.colorBrandBackground2,
    "-webkit-app-region": "drag",
    "-webkit-user-select": "none",
  },
  barTitle: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("0.5rem", "0rem"),
    marginLeft: "0.25rem",
  },
  barLogo: {
    height: "20px",
    width: "20px",
  },
  barButtonContainer: {
    display: "flex",
    ...shorthands.gap("2px", "0rem"),
    marginRight: "0.5rem",
  },
  barButton: {
    cursor: "pointer",
    backgroundColor: tokens.colorStatusWarningBackground3,
    ...shorthands.borderRadius("10%"),
    width: "20px",
    height: "20px",
    textAlign: "center",
    color: "black",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "-webkit-app-region": "no-drag",
  },
  dangerBackground: {
    backgroundColor: tokens.colorPaletteDarkOrangeBackground3,
  },
  cautionBackground: {
    backgroundColor: tokens.colorPaletteYellowBackground3,
  },
  confirmingBackground: {
    backgroundColor: tokens.colorPaletteLightGreenBackground3,
  },
  selectModeContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  selectModeContent: {
    marginTop: "2rem",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  selectModeOptionsGrid: {
    width: "80%",
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
  },
  cardContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  card: {
    height: "9rem",
    width: "7rem",
    display: "flex",
    flexDirection: "column",
    cursor: "pointer",
    alignItems: "center",
    ...shorthands.borderRadius("10px"),
    ...shorthands.padding("0.75rem"),
    backgroundColor: tokens.colorBrandBackground2,
    textAlign: "center",
  },
  cardIconContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  cardIcon: {
    width: "4rem",
    height: "4rem",
  },
});
