#!/usr/bin/env sh
# Temporarily change to a different directory
cd ..

# Run npm test from the project root directory
cd - > /dev/null 2>&1
cmd /c "npm test"
RESULT=$?

# Change back to the original directory
cd -

# Check the test result
if [ $RESULT -eq 0 ]; then
    echo "Tests passed."
    exit 0
else
    echo "Tests failed. Push aborted."
    exit 1
fi